[book]
authors = ["Junwang Zhao"]
language = "en"
multilingual = false
src = "src"
title = "Postgres Weekly, A Hackerâ€™s Digest"

[output.html]
no-section-label = true

[output.html.fold]
enable = true     # whether or not to enable section folding
level = 0         # the depth to start folding
